In [49]:
import pandas as ps

In [50]:
ps.read_csv('SalaryData.csv')

#by default, pandas treat first line as header

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [51]:
dataset = ps.read_csv('SalaryData.csv')

In [62]:
#all columns name.
dataset.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [75]:
#Reterive only one field and store in a variable in pandas.
y = dataset['Salary']

In [76]:
#in numpy, datatype = array
#in pandas, datatype = series

y = y.values #typecasting - converting series to array

In [77]:
Y = y.reshape(-1,1)

In [78]:
x = dataset['YearsExperience']

In [79]:
#convert to numpy or array.
x = x.values

In [80]:
X = x.reshape(-1,1)

In [81]:
from sklearn.linear_model import LinearRegression

In [82]:
model = LinearRegression() #y=b+cx

In [83]:
model.fit(X , Y)

LinearRegression()

In [84]:
model.predict([[10.1]])

array([[121236.81964536]])

In [92]:
c = model.coef_

In [93]:
model.predict([[0]])

array([[25792.20019867]])

In [94]:
#check bias
model.intercept_

array([25792.20019867])

In [95]:
b = model.intercept_

In [96]:
b + c *1.1

array([[36187.15875227]])

In [97]:
model.predict([[1.1]])

array([[36187.15875227]])

In [98]:
import joblib

In [100]:
#everything in model save to salary.pk1 file
#pillow library gives pk1 extension
joblib.dump(model,'Salary.pk1')

['Salary.pk1']